apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        command: ["elasticsearch"]
        securityContext:
          runAsUser: 2000
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  ports:
  - name: elasticsearchtcp
    port: 9300
  - name: elasticsearch
    port: 9200
  selector:
    app: elasticsearch
